### ISSUE TITLE
asdf latest dart should return the latest stable version

### ISSUE THREAD

**Issue by evanweible-wf** [PatOConnor43/asdf-dart#13]
The documentation and CLI help describe `asdf latest <name>` as the command that should "Show Latest Stable Version", but currently for dart it does not filter out beta/dev channel releases so you get something like `2.13.0-114.0.dev`. I saw in another issue thread that there is an option to filtering out beta/dev, but the asdf docs make it sound like that should be the default behavior for `asdf latest`.

By the way, this is awesome - thank you @PatOConnor43!

**Comment by PatOConnor43** [comment]
I think you're right. I had added support for the `dev` and `beta` channels and then added the env vars to hide them to prevent breaking existing behavior. I think it's reasonable to believe that most people using `latest` as a version wouldn't expect something from the `dev` channel.

I just merged a change to exclude those by default. You can pull the updated changes with `asdf plugin-update dart`. Thanks!
