### ISSUE TITLE
Support M1 macs architecture

### ISSUE THREAD

**Issue by maxwellclarke-wf** [PatOConnor43/asdf-dart#24]
Current behavior defaults to downloading x64. In the case of 2.14+ versions, there is an arm64 version for M1 darwin.

Modify the architecture check to point to arm64 if available. I believe it will require a [change here](https://github.com/PatOConnor43/asdf-dart/blob/master/bin/install#L26-L38)

```bash
# on an M1
$> uname -m
arm64
```

**Comment by sagar-tide** [comment]
The support was already added by the author:
https://github.com/PatOConnor43/asdf-dart/pull/16

**Comment by maxwellclarke-wf** [comment]
@sagar-tide it's no coincidence that https://github.com/PatOConnor43/asdf-dart/pull/25 was on the same day I made this request 😛
