### ISSUE TITLE
[Request]please add arm64 support.

### ISSUE THREAD

**Issue by r3jack** [PatOConnor43/asdf-dart#32]
install dart print:

Platform 'linux' supported!
Arch 'aarch64' not supported!

Dart already support arm64.

**Comment by PatOConnor43** [comment]
It should be supported. Can you try `asdf plugin update dart` and then try to install the version again?

Additionally, not every dart version has an arm version. I forget what version they started adding arm support. Maybe 2.13.1?

**Comment by r3jack** [comment]
asdf install dart 3.1.0
Platform 'linux' supported!
Arch 'aarch64' not supported!

**Comment by r3jack** [comment]
I download dart 3.1.0 manually, extract and it works.

**Comment by PatOConnor43** [comment]
Ah this is arm linux. Okay thanks for the report. Do you want to put that change in a PR or would you prefer I push the change?

**Comment by r3jack** [comment]
> Ah this is arm linux. Okay thanks for the report. Do you want to put that change in a PR or would you prefer I push the change?

I'll make a pr.
