### ISSUE TITLE
does not install properly

### ISSUE THREAD

**Issue by malyavka** [PatOConnor43/asdf-dart#5]
For some reason installs are failing for dart 1 and 2.

```
asdf install dart 2
Platform 'darwin' supported!
version
2
/Users/masha/.asdf/installs/dart/2
macos
x64
asdf-dart.xgsQ
0
2
Installing Dart SDK...
https://storage.googleapis.com/dart-archive/channels/stable/release/2/sdk/dartsdk-macos-x64-release.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   234  100   234    0     0   1800      0 --:--:-- --:--:-- --:--:--  1800
Unzipping Dart SDK to /Users/masha/.asdf/installs/dart/2...
```

The zip file downloaded is invalid

**Comment by PatOConnor43** [comment]
Hi thanks for reporting the issue! This is definitely something I should protect against. The expected version should include the minor and patch versions. You can list all the available versions with `asdf list-all dart`. You should be able to use `asdf install dart 2.3.2` to install the latest version.

**Comment by PatOConnor43** [comment]
I also created #6 to document potentially supporting specifying `asdf install dart 2` instead of needing to specify the entire version.

**Comment by PatOConnor43** [comment]
I'm going to close this for now. Please make another issue if you run into any more problems. Thanks!
