### ISSUE TITLE
Plans supporting beta/dev channnel

### ISSUE THREAD

**Issue by niku** [PatOConnor43/asdf-dart#7]
First of all, thank you for creating such a nice plugin. I use almost everyday ❤️ 

Currently, asdf-dart supports only stable channel.
I would appreciate it if you also supports beta and dev channel too.

Do you have any plans to implement it?

**Comment by PatOConnor43** [comment]
Hi, thanks for creating this issue! I can take a look at adding support for those channels this weekend.
