### ISSUE TITLE
Not working for some reason

### ISSUE THREAD

**Issue by watzon** [PatOConnor43/asdf-dart#9]
When everything seems to work fine at first, but it seems as though the package is never actually extracted

```
Platform 'linux' supported!
Version: 2.8.4
Install Path: /home/watzon/.asdf/installs/dart/2.8.4
Platform: linux
Architecture: x64
Downloading to temp directory asdf-dart.HjnW
Include Extras: 0
Major Dart Version: 2
Installing Dart SDK...
https://storage.googleapis.com/dart-archive/channels/stable/release/2.8.4/sdk/dartsdk-linux-x64-release.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  217M  100  217M    0     0  54.8M      0  0:00:03  0:00:03 --:--:-- 54.8M
Unzipping Dart SDK to /home/watzon/.asdf/installs/dart/2.8.4...
```

Running on Arch

**Comment by PatOConnor43** [comment]
Hi @watzon, thanks for the report. Based off the output it does look like you downloaded the zip so that's a good start. By chance, do you have the `unzip` tool installed? I'm currently using Ubuntu but I think you can install it with `sudo pacman -S unzip`. I'm not exactly sure how it will fail if you don't have that. Hope that helps!

**Comment by watzon** [comment]
That's probably it, I don't have unzip installed. Maybe it would be a good idea to have a backup like `7z`?

In the meantime I can always get unzip.

**Comment by PatOConnor43** [comment]
I think when I initially wrote this I tried using `7z x sdk.zip` but it didn't seem to work. I can definitely take another look at that though. I should at least be doing a dependency check before doing anything to give more helpful errors.

**Comment by PatOConnor43** [comment]
Actually I just tried it and it seems to work fine! I'll get a PR up this weekend that allows that and also adds some validation.

**Comment by PatOConnor43** [comment]
As a workaround if you don't want to install `unzip` you can actually just go into `~/.asdf/plugins/dart` and apply this patch. Hope that works for you.
```
diff --git a/bin/install b/bin/install
index e89e28a..2a692da 100755
--- a/bin/install
+++ b/bin/install
@@ -98,7 +98,7 @@ install_dart () {
     fi
 
     echo "Unzipping Dart SDK to $install_path..."
-    unzip -d "$install_path" "$tempdir/sdk.zip" > /dev/null 2>&1
+    7z x "$tempdir/sdk.zip" -o"$install_path" > /dev/null 2>&1
     if [ $allow_extras -eq "1" ]; then
         echo "Unzipping Content Shell to $install_path..."
         unzip -d "$install_path" "$tempdir/content_shell.zip" > /dev/null 2>&1
```

**Comment by watzon** [comment]
Installing unzip isn't an issue. Might be a good idea to check if unzip is installed and throw an error if it isn't though, just so people know what's going on if it doesn't work. I consider this solved so I'll close :)
